enum NavItem {
  dashboard,
  walletSelf,
  walletAll,
  walletOverview,
  transactionCollection,
  transactionTransfer,
  transactionExpense,
  transactionTransactions,
  users,
  roles,
  assignWallets,
  accountReports,
  paymentModes,
  expenseType,
  expenseReport,
  smartApprovals,
  collectionCustomField,
}

